import React, { useState } from 'react';
import { usePortfolioContent } from '../hooks/usePortfolioContent';

export default function ContactPage() {
  const { site } = usePortfolioContent();
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [message, setMessage] = useState('');
  const send = (event) => { event.preventDefault(); const subject = encodeURIComponent(`Portfolio inquiry from ${name || 'a visitor'}`); const body = encodeURIComponent(`${message}\n\nFrom: ${name}${email ? ` <${email}>` : ''}`); window.location.href = `mailto:${site.email}?subject=${subject}&body=${body}`; };
  return <div className="inner-page"><header className="page-hero page-hero--contact"><span className="eyebrow">Contact / opportunities</span><h1>Build something that has to work in the real world.</h1><p>{site.availability}</p></header><section className="contact-layout content-surface"><form onSubmit={send}><div className="contact-pair"><label>Your name<input autoComplete="name" value={name} onChange={(e) => setName(e.target.value)} placeholder="Name" required /></label><label>Your email<input type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@company.com" /></label></div><label>What are you building?<textarea rows="9" value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Tell me about the role, project, research, or collaboration." required /></label><button className="pill-button dark" type="submit">Compose email ↗</button><small>This form opens your email client. The portfolio does not silently store the message or your personal data.</small></form><aside><span className="chapter-kicker">Direct</span><a href={`mailto:${site.email}`}>{site.email}</a><a href={site.github} target="_blank" rel="noreferrer">GitHub ↗</a>{site.linkedin && <a href={site.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a>}<p>{site.location}<br />{site.timezone}</p><span className="contact-note">Best fit: robotics, automation, embedded systems, intelligent software, research, internships, and engineering collaborations.</span></aside></section></div>;
}
