export const site = {
  name: 'Vivek Vala',
  monogram: 'VV',
  role: 'Robotics and Automation Engineer',
  headline: 'Building autonomous mobile robots, embedded hardware, and intelligent software systems.',
  strapline: 'Designing and programming robotics systems that work reliably in the physical world.',
  intro: 'I am a Robotics and Automation Engineering student based in Gujarat, India. My focus is on autonomous navigation with ROS 2, microcontroller firmware, motor control electronics, and computer vision.',
  location: 'Gujarat, India',
  timezone: 'IST (UTC+5:30)',
  email: 'vivekvala562@gmail.com',
  github: 'https://github.com/VivekVRobo',
  linkedinLabel: 'Vivek Vala',
  linkedin: '',
  resumeUrl: '',
  availability: 'Available for robotics engineering internships and project collaborations.',
  stats: [
    ['10', 'Projects Built'],
    ['ROS 2', 'Autonomous Navigation'],
    ['Hardware and Code', 'Complete System Builds'],
  ],
  heroCinema: {
    enabled: true,
    poster: '/hero-cinema-poster.webp',
    webm: '/hero-cinema.webm',
    mp4: '/hero-cinema.mp4',
  },
};

export const capabilities = [
  ['Robotics', 'ROS 2, SLAM, mobile robot navigation, kinematics, Gazebo simulation, sensor fusion'],
  ['Embedded Systems', 'Arduino, ESP32, microcontrollers, motor drivers, circuit design, serial protocols'],
  ['Computer Vision', 'OpenCV, camera tracking, gesture recognition, color and shape sorting'],
  ['Intelligent Systems', 'Local task automation, system tools, Python utilities, speech interfaces'],
  ['Software', 'Python, C++, Linux, Git, automated unit tests, hardware communication'],
];

const projectBase = [
  {
    slug: 'gesture-controlled-robotic-arm', index: '01', eyebrow: 'Robotics & Embedded Systems', title: 'Gesture-Controlled Robotic Arm', shortTitle: 'Gesture Arm',
    summary: 'A 5-DOF articulated robotic arm driven by custom Arduino kinematics firmware, nRF24L01 wireless telemetry, and a wearable IMU sensor glove, verified through continuous physical video actuation.',
    tags: ['Arduino', 'C++', 'Robotics', 'nRF24L01 RF', 'Kinematics', 'MPU6050'], github: 'https://github.com/VivekVRobo/gesture-controlled-robotic-arm', live: '', docs: '', accent: 'clay', scene: 'gesture',
    status: 'Verified physical hardware actuation & continuous video demo (Tier S · 85/100)',
    role: 'Embedded C++ firmware, complementary filter fusion, 4-bar parallel linkage kinematics, and servo actuation.',
    problem: 'Controlling multi-joint robotic arms with buttons or joysticks is unintuitive for untrained operators and lacks spatial mapping fidelity.',
    approach: 'Engineered a wearable gesture glove with MPU6050 6-axis IMU and flex sensing transmitting telemetry packets over nRF24L01 RF to an Arduino controller driving a 5-DOF articulated arm with end-effector gripper.',
    architecture: [
      ['Gesture Sensing', 'MPU6050 6-axis IMU + flex sensor transmitting orientation and finger bend angles'],
      ['Signal Filtering', 'Complementary filter (α=0.96) fusing accelerometer and gyroscope data with deadband'],
      ['Kinematic Mapping', 'Normalizes human spatial range into calibrated servo angles using law-of-cosines IK'],
      ['Wireless Link', 'Low-latency nRF24L01 packet transmission delivering telemetry frames at 50Hz'],
      ['Servo Actuation', 'Dedicated 5V power rail driving TowerPro SG90/MG996R servos (base turntable, shoulder, elbow, gripper)'],
    ],
    decisions: [
      'Implement complementary filtering to cancel IMU drift and high-frequency hand tremors.',
      'Enforce physical angle clamping and servo interpolation to protect gears from sudden acceleration.',
      'Isolate servo power from logic circuitry to prevent voltage brownout resets on motor inrush.',
    ],
    implemented: [
      'Physical articulated arm test bench with SG90/MG996R servos and turntable base',
      'Wearable gesture glove with MPU6050 IMU & flex sensor transmitter',
      'Embedded C++ transmitter and receiver firmware with complementary filter',
      'Continuous 22s hardware demonstration video and bench verification photos',
    ],
    simulated: [
      'Software dry-run verifying reachable Cartesian workspace bounds',
    ],
    planned: [
      'Upgrade to ESP32 BLE / Wi-Fi telemetry bridge',
      'Add closed-loop current sensing on gripper to detect grip torque',
    ],
    testing: 'Empirically tested with live hardware on test bench: captured 22s unbroken continuous video verifying responsive gripper open/close actuation and base turntable panning under ~80ms control latency.',
    lessons: 'Filtering small hand tremors and providing dedicated servo power rails are essential to avoid mechanical chatter and controller brownouts.',
    future: 'Integrate multi-finger independent actuation and closed-loop force feedback on end-effector finger pads.',
    media: [
      { type: 'video', url: '/assets/projects/gesture-arm/gesture-actuation-demo.mp4', label: 'Physical Actuation Demo', caption: 'Continuous uncut physical demonstration: gesture glove driving gripper opening/closing and base panning in real time.' },
      { type: 'image', url: '/assets/projects/gesture-arm/physical-hardware.jpg', label: 'Physical Hardware Bench', caption: 'Articulated arm on test bench showing 4-bar parallel linkage, servos, turntable base, and Arduino controller.' },
      { type: 'image', url: '/assets/projects/gesture-arm/electronics-overview.jpg', label: 'Electronics & Wiring', caption: 'Microcontroller, IMU sensor board, and servo harness breadboard wiring setup.' },
    ],
  },
  {
    slug: 'custom-pcb-motor-driver', index: '02', eyebrow: 'Electronics & Hardware Engineering', title: 'Custom PCB Motor Driver (TI DRV8848)', shortTitle: 'PCB Motor Driver',
    summary: 'A high-thermal-capacity dual H-bridge motor driver PCB for mobile robotics, featuring 2.0 oz finished copper, 3×3 PowerPAD thermal via array, deterministic current chopping, and full first-principles mathematical physics verification.',
    tags: ['KiCad', 'PCB Design', 'DRV8848', 'Power Electronics', 'Thermal Physics', '2.0 oz Cu'], github: 'https://github.com/VivekVRobo/custom-pcb-motor-driver', live: '', docs: '', accent: 'sage', scene: 'pcb',
    status: 'Fabrication package ready · Mathematical physics proof certified (Tier S · 84/100)',
    role: 'Circuit schematic design, component selection, PCB layout, mathematical physics modeling, and design rule verification.',
    problem: 'Standard hobby motor shields lack adequate thermal dissipation, power filtering, and protection against inductive flyback and reverse polarity voltage spikes.',
    approach: 'Engineered a dedicated dual H-bridge board using the TI DRV8848 with 2.0 oz copper, 3×3 thermal via matrix, Vishay 2W metal strip sense resistors, and TVS/fuse protection.',
    architecture: [
      ['Power & Protection', 'Bourns 15V TVS clamp, Littelfuse 3A Nano2 fuse, and Vishay P-FET reverse-polarity stage'],
      ['Driver IC', 'Texas Instruments DRV8848PWPR dual H-bridge with exposed PowerPAD'],
      ['Current Regulation', 'Vishay WSL2512 0.56Ω 2W metal strip sense resistors (0.893A nominal chop, 25.4% derated)'],
      ['Decoupling & Bus', '22µF 1210 X7R MLCC local bypass + 220µF 25V Panasonic hybrid polymer bulk storage'],
      ['Thermal Management', '2.0 oz copper plane with 3×3 thermal via array under PowerPAD (effective θJA = 35.15°C/W)'],
      ['Analytical Proof', 'First-principles physics engine verifying thermal margins (>39°C headroom at 50°C) and IPC-2152 trace ampacity'],
    ],
    decisions: [
      'Use 2.0 oz finished copper (70µm) to reduce trace resistance to 4.03 mΩ and drop conductor Joule heating to <0.22°C.',
      'Implement a 9-via thermal array (0.3mm drill) directly beneath the PowerPAD tied into the solid bottom ground plane.',
      'Derate sense resistor power to 25.4% of maximum rating, easily exceeding military/aerospace 50% derating standards.',
    ],
    implemented: [
      'Complete KiCad schematic capture and DRC-clean 2-layer PCB layout (48.0 x 36.0 mm)',
      'Production RS-274X Gerber and Excellon drill package with SHA-256 integrity hash (gerbers_drv8848_revA.zip)',
      '100% active, orderable BOM with verified manufacturer part numbers passing automated linters',
      'Deterministic mathematical physics validation engine (tools/math_physics_engine.py)',
      'Automated regression test suite with 23/23 unit and physics tests passing',
      'Staged 5-tier first-article hardware bring-up and measurement protocol',
    ],
    simulated: [
      'Deterministic 16-corner datasheet tolerance sweep (artifacts/corner-sweep.json)',
      'Conjugate heat transfer modeling verifying θJA = 35.15°C/W and TJ = 88.1°C in 25°C lab ambient',
      'IPC-2152 conductor trace heating equations and DC bus step transient voltage droop (0.824%)',
    ],
    planned: [
      'Fabricate 5 prototype boards via JLCPCB/PCBWay (2.0 oz Cu, Lead-Free HASL)',
      'Execute 5-tier bench bring-up protocol and log oscilloscope PWM rise times and thermal camera imaging under 1.0A load',
    ],
    testing: 'Automated linters and pytest test suite (23/23 passed) verify netlist contracts, BOM traceability, KiCad footprints, current regulation limits, and thermal physics equations.',
    lessons: 'Thermal dissipation cannot be an afterthought: incorporating 2.0 oz copper pours and direct thermal vias reduces silicon operating temperatures by over 12°C compared to standard 1.0 oz boards.',
    future: 'Fabricate physical board run, assemble with SMD reflow hot plate, and record thermal camera imaging on test bench.',
    media: [
      { type: 'image', url: '/assets/projects/pcb-motor-driver/pcb-system-architecture.svg', label: 'System Architecture', caption: 'Complete power path, protection front-end, TI DRV8848 dual H-bridges, and current-sense loops.' },
      { type: 'image', url: '/assets/projects/pcb-motor-driver/pcb-thermal-stackup.svg', label: 'Thermal Stackup & Physics', caption: '2.0 oz finished copper cross-section, 3×3 thermal via array under PowerPAD, and conjugate heat dissipation proof.' },
      { type: 'image', url: '/assets/projects/pcb-motor-driver/pcb-board-layout.svg', label: 'CAD Board Layout', caption: 'Dimensioned 48.0 × 36.0 mm PCB layout, 4× M3 isolated mounting holes, 60 mil power traces, and test points.' },
    ],
  },
  {
    slug: 'slam-robot-ros2', index: '03', eyebrow: 'Autonomous Mobile Robotics', title: 'SLAM Robot with ROS 2', shortTitle: 'SLAM Robot',
    summary: 'An autonomous mobile robot running ROS 2 and SLAM navigation in Gazebo, with ground truth trajectory tracking and mapping evaluation tools.',
    tags: ['ROS 2', 'SLAM', 'Gazebo', 'LiDAR', 'Navigation'], github: 'https://github.com/VivekVRobo/slam-robot-ros2', live: '', docs: '', accent: 'mist', scene: 'slam',
    status: 'ROS 2 Nav2 & SLAM simulation benchmarking (Tier S · 82/100)',
    role: 'ROS 2 package development, simulation setup, benchmark tools, and documentation.',
    problem: 'Many SLAM demonstrations show a map screenshot without testing if the run is repeatable or comparing the path against true simulator position.',
    approach: 'Built a structured evaluation setup in Gazebo where trajectory accuracy, mapping consistency, and sensor data can be tested repeatedly.',
    architecture: [
      ['Gazebo World', 'Differential drive robot model, indoor obstacle room, and simulated LiDAR sensor'],
      ['ROS 2 Graph', 'Laser scan, odometry, coordinate transforms, and SLAM mapping node'],
      ['Recorder', 'Saves estimated robot trajectory and true simulator position into structured files'],
      ['Evaluation', 'Calculates trajectory error, path drift, and resource usage across test runs'],
      ['Test Runs', 'Automated replay scripts and reproducible evaluation datasets'],
    ],
    decisions: [
      'Separate simulated wheel odometry from simulator ground truth position.',
      'Test mapping consistency across multiple runs instead of relying on a single demo.',
      'Record evaluation data into readable formats for easy inspection.',
    ],
    implemented: ['ROS 2 workspace and launch files', 'Gazebo robot model and indoor world', 'Path evaluation scripts', 'Automated recording tools'],
    simulated: ['Gazebo simulation environment and offline path evaluators'],
    planned: ['Record bag files from physical LiDAR and encoders', 'Run identical evaluation scripts on real differential drive hardware'],
    testing: 'Software and simulation tests verify node communication, transform trees, and trajectory scoring tools.',
    lessons: 'Autonomous mapping is much easier to evaluate when ground truth data is recorded side by side with estimated position.',
    future: 'Deploy the tested navigation stack onto a physical differential drive robot with real LiDAR and wheel encoders.',
    media: [
      { type: 'placeholder', label: 'Simulation World', caption: 'Gazebo environment with differential drive robot and LiDAR' },
      { type: 'placeholder', label: 'Trajectory Evaluation', caption: 'Comparison of estimated path against true simulator position' },
      { type: 'placeholder', label: 'Generated Map', caption: 'Occupancy grid map generated during autonomous navigation' },
    ],
  },
  {
    slug: '3dof-robotic-arm', index: '04', eyebrow: 'Analytical Kinematics & Modeling', title: '3-DOF Kinematics & Trajectory Solver', shortTitle: '3-DOF Kinematics',
    summary: 'A tabletop robotic arm programmed with forward and inverse kinematics algorithms, servo calibration tools, and Arduino firmware to reach 3D coordinates.',
    tags: ['Python', 'Arduino', 'Inverse Kinematics', 'Servo Motors', 'Mechatronics'], github: 'https://github.com/VivekVRobotics/3dof-robotic-arm', live: '', docs: '', accent: 'clay', scene: 'arm',
    status: 'Analytical inverse kinematics & Cartesian trajectory engine (Tier A · 78/100)',
    role: 'Kinematic modeling, Cartesian motion planning, Arduino firmware, and servo calibration.',
    problem: 'A robotic arm requires coordinated joint motion to reach a 3D target point accurately while respecting joint limits and mechanical offsets.',
    approach: 'Developed analytic inverse kinematics in Python, mapped angles to calibrated PWM servo signals, and sent coordinates over serial to Arduino.',
    architecture: [
      ['Target Input', 'Cartesian coordinates and straight line waypoint generator'],
      ['Kinematics', 'Trigonometric base yaw, shoulder, and elbow angle solver'],
      ['Joint Limits', 'Software boundary checks to prevent mechanical collisions'],
      ['Servo Mapping', 'Individual calibration curves for each servo motor'],
      ['Arduino Firmware', 'Serial command parser and smooth servo controller'],
    ],
    decisions: ['Keep link lengths and angular limits configurable.', 'Validate kinematics math in software before commanding real servos.', 'Measure physical endpoint accuracy with real markers.'],
    implemented: ['Forward and inverse kinematics math', 'Straight line waypoint interpolation', 'Servo calibration tools', 'Arduino receiver sketch and serial interface'],
    simulated: ['Software dry run verifying reachable target space'],
    planned: ['Record physical tip position measurements', 'Tune servo PID response for smoother motion'],
    testing: 'Unit tests verify mathematical consistency between forward and inverse kinematics across hundreds of reachable points.',
    lessons: 'Accurate manipulator control depends on realistic joint limit checks and careful individual servo offset calibration.',
    future: 'Integrate a small camera for visual targeting and coordinate grasping of objects on a table.',
    media: [
      { type: 'placeholder', label: 'Arm Assembly', caption: '3D printed arm links with servo motors and base turntable' },
      { type: 'placeholder', label: 'Kinematics Diagram', caption: 'Coordinate frames and joint angle solutions' },
      { type: 'placeholder', label: 'Workspace Reach', caption: 'Calculated reachable workspace in Cartesian coordinates' },
    ],
  },
  {
    slug: 'jarvis', index: '05', eyebrow: 'Software and Automation', title: 'JARVIS Desktop Assistant', shortTitle: 'JARVIS',
    summary: 'A desktop automation system written in Python that integrates speech recognition, system tools, and task automation on Windows.',
    tags: ['Python', 'Speech Recognition', 'Automation', 'System Tools', 'Windows'], github: 'https://github.com/VivekVRobo/jarvis', live: '', docs: '', accent: 'sand', scene: 'intelligence',
    status: 'Core desktop automation and voice tools functional',
    role: 'Software architecture, speech processing, tool dispatch, and desktop integration.',
    problem: 'Voice assistants often rely entirely on heavy cloud APIs or become brittle when trying to automate local computer tasks.',
    approach: 'Created a modular Python system with clear command routing, local speech synthesis, and direct operating system tool hooks.',
    architecture: [
      ['Speech Input', 'Microphone audio capture and offline speech recognition'],
      ['Command Router', 'Matches spoken phrases to specific local actions and tools'],
      ['Tool Modules', 'Application launching, file organization, volume, and browser control'],
      ['Local Storage', 'Saves user preferences, shortcuts, and command history'],
      ['Hardware Hooks', 'Optional serial link to external Arduino status indicators'],
    ],
    decisions: ['Prioritize fast local actions over slow cloud round trips.', 'Keep tool execution explicit and safe without dangerous shell commands.', 'Provide voice confirmation for actions.'],
    implemented: ['Voice recognition loop', 'System command tools', 'Audio feedback engine', 'Configuration files'],
    simulated: [],
    planned: ['Add lightweight local language model parsing for flexible phrasing', 'Build a clean system tray interface'],
    testing: 'Interactive CLI testing verifies voice intent matching, tool execution, and error handling when microphone input is noisy.',
    lessons: 'Direct, deterministic command matching is much faster and more reliable for daily desktop shortcuts than open ended generation.',
    future: 'Expand hardware integration to control desk lighting and read temperature sensors via serial communication.',
    media: [
      { type: 'placeholder', label: 'Voice Command Interface', caption: 'Audio capture loop and intent recognition' },
      { type: 'placeholder', label: 'System Tools', caption: 'Application launch and Windows automation modules' },
      { type: 'placeholder', label: 'Hardware Link', caption: 'Serial communication with Arduino status display' },
    ],
  },
  {
    slug: 'aurelia-chan', index: '06', eyebrow: 'Conversational AI', title: 'Aurelia AI Runtime', shortTitle: 'Aurelia Runtime',
    summary: 'An experimental conversational AI runtime exploring persistent memory, interaction state, and natural dialogue.',
    tags: ['Python', 'Flask', 'SQLite', 'Dialogue Systems', 'State Management'], github: 'https://github.com/VivekVRobo/Aurelia-Chan-Source', live: '', docs: '', accent: 'rose', scene: 'aurelia',
    status: 'Dialogue runtime and memory module functional',
    role: 'Backend runtime, persistent memory design, state engine, and API integration.',
    problem: 'Simple chatbots forget context immediately between sessions and lack structured state to track user interaction history.',
    approach: 'Structured a modular Python backend with SQLite persistence, conversation memory buffers, and clear separation between dialogue logic and presentation.',
    architecture: [
      ['Runtime Server', 'Flask API handling conversation requests and responses'],
      ['Dialogue Engine', 'Context aware prompt construction and response processing'],
      ['Memory Store', 'SQLite database storing conversation logs and user facts'],
      ['State Manager', 'Tracks active topic and mood state between exchanges'],
      ['Frontend Stage', 'Clean web interface for text and audio conversation'],
    ],
    decisions: ['Store persistent conversation logs locally in SQLite.', 'Separate response logic from the web interface for easy testing.', 'Validate API responses to prevent crashes on malformed data.'],
    implemented: ['Flask API server', 'SQLite conversation storage', 'State tracking engine', 'Web chat interface'],
    simulated: [],
    planned: ['Add vector similarity search for retrieving older conversation memories', 'Improve response streaming speed'],
    testing: 'API endpoint tests verify session creation, message persistence, and memory retrieval across restarts.',
    lessons: 'A persistent memory store dramatically improves conversational continuity compared to stateless prompt loops.',
    future: 'Connect the dialogue system to external robotics interfaces for physical conversation demonstrations.',
    media: [
      { type: 'placeholder', label: 'Conversation Interface', caption: 'Web based dialogue interface with live chat history' },
      { type: 'placeholder', label: 'Memory Architecture', caption: 'SQLite schema for context and user memory persistence' },
      { type: 'placeholder', label: 'State Tracking', caption: 'Context and topic tracking across conversation turns' },
    ],
  },
  {
    slug: 'http-server-from-scratch', index: '07', eyebrow: 'Systems Software', title: 'HTTP Server from Scratch', shortTitle: 'HTTP Server',
    summary: 'A custom HTTP web server written in C++ using POSIX socket programming to handle TCP connections, HTTP requests, and static files.',
    tags: ['C++', 'Socket Programming', 'Networking', 'HTTP Protocol', 'Linux'], github: 'https://github.com/VivekVRobo/http-server-from-scratch', live: '', docs: '', accent: 'graphite', scene: 'server',
    status: 'Socket engine and HTTP parser verified',
    role: 'Network programming, HTTP request parser, thread pool concurrency, and file serving.',
    problem: 'Using high level web frameworks hides the fundamental mechanics of network sockets, TCP handshakes, request parsing, and concurrent connection handling.',
    approach: 'Built a low level server in C++ using Berkeley sockets, implemented an incremental HTTP parser, and handled concurrent clients with a thread pool.',
    architecture: [
      ['Socket Layer', 'TCP socket creation, binding, listening, and accepting client connections'],
      ['Request Parser', 'Parses HTTP request method, URI, headers, and body from raw byte buffers'],
      ['Static File Engine', 'Safely maps URLs to local files with path traversal security checks'],
      ['Thread Pool', 'Worker thread queue to handle multiple concurrent clients efficiently'],
      ['Response Builder', 'Generates valid HTTP response headers and status codes'],
    ],
    decisions: ['Use raw sockets to thoroughly understand network protocols.', 'Sanitize file paths to prevent directory traversal vulnerabilities.', 'Use nonblocking sockets to handle slow clients gracefully.'],
    implemented: ['TCP socket server', 'HTTP request parser', 'Thread pool manager', 'Static file handler with MIME types'],
    simulated: [],
    planned: ['Implement keep alive persistent connections', 'Add HTTPS support with OpenSSL'],
    testing: 'Automated test suite validates HTTP method parsing, 404 handling, file serving, and concurrent client requests.',
    lessons: 'Handling partial TCP reads and socket timeouts properly is the most challenging part of raw network programming.',
    future: 'Benchmark throughput against standard lightweight servers and optimize socket buffer recycling.',
    media: [
      { type: 'placeholder', label: 'Server Architecture', caption: 'Socket listening loop, thread pool queue, and request handlers' },
      { type: 'placeholder', label: 'HTTP Parser', caption: 'Byte buffer parsing and HTTP header tokenization' },
      { type: 'placeholder', label: 'Concurrency Test', caption: 'Simultaneous client requests handled across thread workers' },
    ],
  },
  {
    slug: 'line-following-robot', index: '08', eyebrow: 'Mobile Robotics', title: 'Line Following Robot', shortTitle: 'Line Follower',
    summary: 'An autonomous wheeled robot with an infrared sensor array and PID control loop for smooth line tracking at variable speeds.',
    tags: ['Arduino', 'IR Sensors', 'PID Control', 'Mobile Robotics', 'Motors'], github: 'https://github.com/VivekVRobo/line-following-robot', live: '', docs: '', accent: 'sage', scene: 'line',
    status: 'Firmware and sensor calibration verified',
    role: 'Robot chassis assembly, sensor calibration, PID control algorithm, and motor tuning.',
    problem: 'Simple threshold line following causes jerky zig zag motion and loses the line easily at curves or junctions.',
    approach: 'Used an array of 5 analog IR sensors to calculate weighted position error, fed into a PID algorithm that smoothly modulates dual DC motor speeds.',
    architecture: [
      ['Sensor Array', 'Five analog reflective optical sensors positioned across the line'],
      ['Position Estimator', 'Weighted average calculation giving a continuous line position error'],
      ['PID Controller', 'Proportional, integral, and derivative terms calculate turning correction'],
      ['Motor Mixer', 'Applies differential PWM signals to left and right DC motor drivers'],
      ['Recovery Logic', 'Memory of last seen direction when the line is temporarily lost'],
    ],
    decisions: ['Calibrate sensor minimum and maximum readings on each boot.', 'Use differential motor braking for sharper turns.', 'Keep PID constants easily tunable via serial monitor.'],
    implemented: ['Sensor calibration routine', 'Weighted position algorithm', 'PID control loop in C++', 'Motor driver PWM interface'],
    simulated: [],
    planned: ['Add wheel encoders to measure travel speed and distance', 'Design an optimized custom chassis'],
    testing: 'Sensor response testing across varied line thicknesses and contrast levels, with tuned PID coefficients for 90 degree curves.',
    lessons: 'Sensor calibration is just as important as the control algorithm for reliable performance across different floor lighting conditions.',
    future: 'Add obstacle detection using an ultrasonic sensor to stop and navigate around track blockages.',
    media: [
      { type: 'placeholder', label: 'Robot Hardware', caption: 'Two wheel chassis with 5 sensor array and motor driver' },
      { type: 'placeholder', label: 'Sensor Calibration', caption: 'Analog reading normalization across black and white surfaces' },
      { type: 'placeholder', label: 'Track Performance', caption: 'Smooth trajectory tracking through curves and intersections' },
    ],
  },
  {
    slug: 'cv-object-sorter', index: '09', eyebrow: 'Computer Vision', title: 'Computer Vision Object Sorter', shortTitle: 'Vision Sorter',
    summary: 'A real time vision pipeline built with OpenCV and Python to detect, classify, and sort objects based on color and shape contours.',
    tags: ['Python', 'OpenCV', 'Computer Vision', 'Automation', 'Arduino'], github: 'https://github.com/VivekVRobo/cv-object-sorter', live: '', docs: '', accent: 'sky', scene: 'sorter',
    status: 'Detection and sorting pipeline functional',
    role: 'Camera calibration, HSV color thresholding, contour detection, and Arduino servo triggering.',
    problem: 'Industrial automation requires separating items accurately based on visual features under changing ambient light.',
    approach: 'Built a webcam vision pipeline that converts frames to HSV color space, filters noise with morphological operations, and commands an Arduino sorting diverter.',
    architecture: [
      ['Video Capture', 'High frame rate camera acquisition with fixed exposure settings'],
      ['Color Segmentation', 'HSV color space thresholding for robust color isolation'],
      ['Shape Analysis', 'Contour detection to calculate object area and centroid coordinates'],
      ['Trigger Zone', 'Virtual gate on screen that detects when an object reaches the diverter'],
      ['Serial Interface', 'Sends single byte sorting commands to an Arduino servo motor'],
    ],
    decisions: ['Use HSV color space instead of RGB to reduce sensitivity to brightness changes.', 'Filter small noise contours to avoid false triggers.', 'Debounce triggers so one object only fires one action.'],
    implemented: ['OpenCV processing script', 'Real time threshold adjustment trackbars', 'Serial communication protocol', 'Arduino diverter sketch'],
    simulated: [],
    planned: ['Add barcode and QR code recognition', 'Support conveyor belt continuous feed'],
    testing: 'Tested accuracy across colored wooden blocks under varied lighting levels, verifying correct sorting decisions.',
    lessons: 'Consistent lighting and camera exposure are critical prerequisites for reliable color based vision pipelines.',
    future: 'Train a lightweight machine learning classifier to identify object types beyond simple color thresholds.',
    media: [
      { type: 'placeholder', label: 'Vision Processing', caption: 'Camera feed with HSV threshold mask and detected object contours' },
      { type: 'placeholder', label: 'Sorting Mechanism', caption: 'Arduino controlled servo arm routing objects into bins' },
      { type: 'placeholder', label: 'Classification UI', caption: 'Live user interface displaying detected color, area, and count' },
    ],
  },
  {
    slug: 'robotic-character-interface', index: '10', eyebrow: 'Interactive Robotics', title: 'Robotic Character Interface', shortTitle: 'Character Robot',
    summary: 'An expressive physical robot with animated eyes and head pan and tilt servos that responds to user presence and interactions.',
    tags: ['Arduino', 'Servo Motors', 'Display Animation', 'Physical Computing', 'C++'], github: 'https://github.com/VivekVRobo/robotic-character-interface', live: '', docs: '', accent: 'rose', scene: 'rci',
    status: 'Display interface and servo movement functional',
    role: 'Mechanical pan tilt design, display animation programming, and interactive behaviors.',
    problem: 'Robots often feel cold and mechanical, making human interaction feel unnatural and intimidating.',
    approach: 'Combined two servo motors for head movement with a small LCD display showing animated expressive eyes, creating friendly physical feedback.',
    architecture: [
      ['Pan Tilt Mechanism', 'Two servo motors providing horizontal pan and vertical tilt movement'],
      ['Display Graphics', 'Draws animated eye graphics with blinking and gaze shifts on an LCD'],
      ['Sensors', 'Ultrasonic sensor detecting when a person approaches the robot'],
      ['Behavior Controller', 'State machine switching between idle searching and attentive gaze modes'],
      ['Chassis', 'Compact 3D printed desktop enclosure holding electronics and servos'],
    ],
    decisions: ['Use parametric curves for smooth eye blinking animations.', 'Randomize idle head movements to make the robot feel alert and alive.', 'Keep power for servos separate from the microcontroller.'],
    implemented: ['Display rendering library', 'Pan tilt servo control', 'Proximity detection logic', 'Interactive state machine'],
    simulated: [],
    planned: ['Add a microphone for reacting to clapping or speech', 'Include capacitive touch sensors on the robot head'],
    testing: 'Tested continuous operation of servo movements and LCD refresh rates, confirming smooth 60 FPS eye animations.',
    lessons: 'Subtle timing variations and smooth eye acceleration make a machine feel dramatically more approachable to humans.',
    future: 'Integrate face tracking using a small camera so the robot maintains direct eye contact with people walking by.',
    media: [
      { type: 'placeholder', label: 'Animated Eyes', caption: 'LCD screen rendering blinking and expressive gaze animations' },
      { type: 'placeholder', label: 'Pan Tilt Mechanism', caption: 'Dual servo mechanical bracket for horizontal and vertical rotation' },
      { type: 'placeholder', label: 'Desktop Robot', caption: 'Assembled interactive character robot on desk enclosure' },
    ],
  },
];

export const projects = projectBase.map((project, i) => ({ ...project, id: project.slug, featured: i < 6, published: true, order: i }));

export const labProjects = [
  { title: 'Aethel Visual Studio', meta: 'High-Resolution Visual Art, 8K Masters', status: 'Production Studio', detail: 'Dedicated visual art direction and verified 4K/8K master workflow for creators, games, music, publishing, and brands.', live: 'https://aethel-visual-studio.vercel.app/' },
  { title: 'Universal Brain', meta: 'Local Automation Engine', status: 'Active Development', detail: 'A local engine for coordinating Python scripts, desktop automation, and developer tools on Windows.' },
  { title: 'Native Desktop Pet', meta: 'Windows Desktop Animation', status: 'Prototype', detail: 'A transparent desktop character program with sprite animations, system tray controls, and status reminders.' },
  { title: 'Media Automation Pipeline', meta: 'Python, Playwright, Automation', status: 'Tool in Use', detail: 'An automated media processing and publishing tool with scheduled tasks, image resizing, and error logging.' },
  { title: 'Video Studio Workflow', meta: 'Computer Vision, FFmpeg, Python', status: 'Experimental', detail: 'A modular video processing pipeline for automated clipping, audio normalization, and format conversion.' },
  { title: 'Audio Library Engine', meta: 'Audio Management, Python', status: 'Subsystem', detail: 'A local audio selector and playback utility that categorizes tracks and manages playlists for experiments.' },
  { title: 'Workflow Assistant', meta: 'Python, Automation, Data', status: 'Tool in Use', detail: 'A set of scripts for automated data extraction, formatting, and report generation for engineering projects.' },
  { title: 'Webcam Gesture Controller', meta: 'OpenCV, Arduino, Serial', status: 'Working Prototype', detail: 'A webcam based differential drive controller that translates hand gestures into motor drive commands.', github: 'https://github.com/VivekVRobo/gesture-controlled-robot' },
];

export const experience = [
  { period: '19 June to 3 July 2026', role: 'Embedded Systems Intern', org: 'Corporate Web Solutions', detail: 'Hands on experience with Embedded C, microcontrollers, GPIO interfacing, UART serial communication, buffers, and firmware architecture.' },
];

export const education = [
  { period: 'Current', role: 'B.E. Robotics and Automation Engineering', org: 'Government Engineering College, Gandhinagar, Gujarat Technological University', detail: 'Undergraduate degree focusing on robotics, control systems, embedded electronics, computer vision, and autonomous navigation.' },
];

export const blogPosts = [
  { slug: 'building-reliable-robots', date: 'Engineering Note 01', title: 'Building reliable robots with clear verification', excerpt: 'Why robotics projects become stronger when simulation, hardware testing, and real measurements are clearly documented.', body: ['A visually impressive demo is exciting, but clear engineering documentation is what makes a project trustworthy.', 'When developing robotics systems, I make sure to document the exact hardware specs, code setup, sensor calibrations, and observed results.', 'The goal is to produce honest engineering work that anyone can inspect, verify, and learn from.'] },
  { slug: 'connecting-mechanical-and-code', date: 'Engineering Note 02', title: 'Connecting mechanical parts with microcontroller code', excerpt: 'What building a robotic arm taught me about mechanical limits, motor calibration, and software geometry.', body: ['The most interesting challenge in robotics is the intersection between physical parts and software.', 'A mathematical target point can look perfect on paper, but the real servo might have backlash, cable tension, or slightly different link lengths.', 'Solving those real world discrepancies is where robotics engineering becomes practical and rewarding.'] },
  { slug: 'local-first-automation', date: 'Engineering Note 03', title: 'Why I focus on local and lightweight automation tools', excerpt: 'The benefits of building fast, local desktop automation tools that work directly on your machine.', body: ['Heavy cloud services can be slow and unpredictable for simple desktop tasks.', 'Building local Python utilities with direct system access makes daily development workflows much faster, private, and dependable.', 'Focusing on lightweight tools that do one job well is often the best engineering approach.'] },
];

export function findProject(slug) { return projects.find((project) => project.slug === slug); }

export function relatedProjects(project, allProjects = projects, limit = 3) {
  const tags = new Set(project.tags || []);
  return allProjects
    .filter((item) => item.slug !== project.slug && item.published !== false)
    .map((item) => ({
      item,
      score: (item.eyebrow === project.eyebrow ? 4 : 0)
        + (item.scene === project.scene ? 2 : 0)
        + (item.tags || []).reduce((sum, tag) => sum + (tags.has(tag) ? 2 : 0), 0),
    }))
    .sort((a, b) => b.score - a.score || (a.item.order ?? 99) - (b.item.order ?? 99))
    .slice(0, limit)
    .map(({ item }) => item);
}
